Resources:
  GearSpotterS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: gearspotter.com
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
  DNS: 
    Type: AWS::Route53::HostedZone
    Properties: 
      Name: gearspotter.com
  DNSRecords:
    Type: AWS::Route53::RecordSetGroup
    Properties: 
      HostedZoneName: gearspotter.com.
      RecordSets:
        - Name: gearspotter.com
          Type: A
          TTL: 60
          ResourceRecords:
          - 95.85.42.227
        - Name: gearspotter.com
          Type: TXT
          TTL: 60
          ResourceRecords:
          - "\"google-site-verification=zqp-XfyLM_-Y63YGVrq2gFz365kTWjhHlhjf9E6H7NU\""
        - Name: gearspotter.com
          Type: MX
          TTL: 60
          ResourceRecords:
          - 1 aspmx.l.google.com
          - 5 alt1.aspmx.l.google.com
          - 5 alt2.aspmx.l.google.com
          - 10 aspmx2.googlemail.com
          - 10 aspmx3.googlemail.com
