Resources:
  GearSpotterS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: gs-landing
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
